[package]
name = "thirtyfour-stealth"
version = "0.1.2"
edition = "2021"
description = "A stealthy, undetected implementation of thirtyfour for web automation"
repository = "https://github.com/0xpatryk/thirtyfour-stealth"
license = "MIT"
readme = "README.md"
keywords = ["selenium", "webdriver", "automation", "scraping", "stealth"]
categories = ["web-programming", "api-bindings", "development-tools"]
authors = ["Patryk Stemporowski <patryk.stemporowski@gmail.com>"]
documentation = "https://docs.rs/thirtyfour-stealth"
homepage = "https://github.com/0xpatryk/thirtyfour-stealth"
rust-version = "1.89"

[dependencies]
async-trait = "0.1.89"
rand = "0.9.2"
reqwest = { version = "0.12.23", default-features = false, features = ["rustls-tls"] }
serde_json = "1.0.143"
thirtyfour = "0.36.1"
tokio = "1.47.1"
zip = "2.4.2"
tracing = "0.1.41"
